name: Configuration of synthetizer 

year: 2016

Households Variables: 
 - children
 - hhincome
 #- persons
 #- cars
 #- nhouseholds

Persons variables:
 - age
 - sex
 #- grade
 #- emp
 #- commute
 #- race

census configuration: 
 config acs:  'C:\\Users\\xgitiaux\Documents\\Research and Analysis\\Synthetizer\\Data\\Inputs\\config_ACS_variables.yaml'
 key: #####
 base_url: 'https://api.census.gov/data/year/acs/acs5?get=NAME,variables&for=block%20group:*&in=in_field&key=your_key'
 geo_url: 'https://www2.census.gov/geo/docs/reference/codes/files/st08_co_cou.txt'
 pums_url: 'https://www2.census.gov/programs-surveys/acs/data/pums/year/5-Year/'

optimization configuration:
 losstol: 2.2
 chatol: 0.0001
 eta: 1.0
 number of epochs: 10

number of households: 2168940


